matrix:
  include:
    - os: linux
      install: source .ci/install-ubuntu-texlive.sh
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - os: osx
      addons:
        homebrew:
          packages:
            - gnu-sed
          casks:
            - basictex
          update: true
      install: source .ci/install-macos-basictex.sh

before_script:
  - source scripts/unpack.sh
  - sed -i 's/documentclass\[/documentclass[fontset=fandol, /' sample/thesis.tex

script:
  - latexmk -cd -quiet -halt-on-error -time -xelatex sample/thesis.tex
